config {
  type: "operations",
  tags: ["setup"],
  hasOutput: true,
  schema: "walmart_raw",
  name: "sales_train_validation.sqlx"
}

CREATE OR REPLACE EXTERNAL TABLE ${self()}
(
  id STRING,
  item_id STRING
  dept_id STRING
  cat_id STRING
  store_id STRING
  ${selectDayColumns(1, 1913, 'd_')}
)
OPTIONS (
  format = 'CSV',
  uris = ['https://storage.googleapis.com/m5_raw/sales_train_validation.csv'],
  skip_leading_rows = 1
);