config {
  type: "operations",
  tags: ["setup"],
  hasOutput: true,
  schema: "config_business",
  name: "country_lookup"
}

CREATE OR REPLACE EXTERNAL TABLE ${self()}
(
  iso_abbreviation STRING,
  country_name STRING,
)
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/1gq-KAr4e03Y2IxFZN_knQWQvCn0pW_mU9mYV-Lkr8cg/edit?usp=drive_web&ouid=103844197302772851363'],
  skip_leading_rows = 1
);