config {
  type: "operations",
  tags: ["setup"],
  hasOutput: true,
  schema: "config_business",
  name: "customer_segments"
}

CREATE OR REPLACE EXTERNAL TABLE ${self()}
(
  segment_name STRING,
  gender STRING,
  age_min INT64,
  age_max INT64,
  target_max_age INT64,
)
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/1qmTtMT3hOnGR0hUUqhGnH3E9gjsyeGkYauSNs7d_d98/edit?gid=0#gid=0'],
  skip_leading_rows = 1
);