Table trx_fct {
    order_id integer [pk]
    product_id integer [pk]
    inventory_item_id integer [pk]
    user_id integer
    date date
    product_brand string
    product_category string
    user_segment string
    market string
    sale_price NUMERIC
    product_cost NUMERIC
    gross_profit NUMERIC
}
Table inventory_dim {
    inventory_item_id integer [pk]
    date_created date
    date_sold date
}
Table event_fct {
    event_id integer [pk]
    user_id integer
    sequence_number integer
    session_id integer
    date_created date
    traffic_source string
    uri string
    event_type string
}
Table order_dim {
    order_id integer [pk]
    status string
    date_created date
    date_returned date
    date_shipped date
    date_delivered date
    num_of_item ingeger
    order_processing_time time
    order_transit_time time
    order_lead_time time
}
Table product_dim {
    product_id integer [pk]
    cost NUMERIC
    category string
    brand string
    retail_price NUMERIC
    product_markup NUMERIC
    department string
}
Table user_dim {
    user_id integer [pk]
    age integer
    gender string
    country string
    market string
    demographic_segment string
    date_created date
}

Ref: trx_fct.order_id > order_dim.order_id
Ref: trx_fct.product_id > product_dim.product_id
Ref: trx_fct.inventory_item_id - inventory_dim.inventory_item_id
Ref: trx_fct.user_id > user_dim.user_id

Ref: event_fct.user_id > user_dim.user_id